### ISSUE TITLE
Špatný format citací BibTex

### ISSUE THREAD

**Issue by yakuta-stu** [xkapustap/clanok#1]
Doporučil bych změnit názvy citací v BibTex souboru, aby se v nich bylo možné snadněji zorientovat. Například z názvu `7148493` není jasné, o jakou citaci jde. Osobně bych doporučil používat format `PříjmeníRok` - například `Sharma2015`

**Comment by xkapustap** [comment]
Ok.

**Comment by xkapustap** [comment]
Ok.

**Comment by yakuta-stu** [comment]
Přesto jsem to upravil.

**Comment by yakuta-stu** [comment]
#a33d5b4a3541e9f1556ce3b29aa9188ca1315dbc
